apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: ocp-pipelines-demo-app-trigger
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: ocp-pipelines-demo-app-github-secret
            secretKey: secretToken
        - name: "eventTypes"
          value: ["push"]
  bindings:
    - ref: ocp-pipelines-demo-app-trigger-binding
  template:
    ref: ocp-pipelines-demo-app-trigger-template
---
apiVersion: v1
kind: Secret
metadata:
  name: ocp-pipelines-demo-app-github-secret
type: Opaque
stringData:
  secretToken: "1234567"